version: 1.0.{build}
clone_depth: 1
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore AvalonTerminal.sln
build:
  project: AvalonTerminal.sln
  verbosity: minimal